'use strict';

const SUGGESTION_STATUS = Object.freeze({
  NEW: 'new',
  TRIAGED: 'triaged',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
  IMPLEMENTED: 'implemented',
});

const SUGGESTION_TYPES = Object.freeze([
  'data_error',
  'missing_place',
  'hierarchy',
  'translation',
  'other',
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [SUGGESTION_STATUS.NEW]: [SUGGESTION_STATUS.TRIAGED],
  [SUGGESTION_STATUS.TRIAGED]: [SUGGESTION_STATUS.ACCEPTED, SUGGESTION_STATUS.REJECTED],
  [SUGGESTION_STATUS.ACCEPTED]: [SUGGESTION_STATUS.IMPLEMENTED],
  [SUGGESTION_STATUS.REJECTED]: [],
  [SUGGESTION_STATUS.IMPLEMENTED]: [],
});

const PUBLIC_LIMITS = Object.freeze({
  TITLE_MAX: 160,
  DESCRIPTION_MAX: 4000,
  DISPLAY_NAME_MAX: 120,
  TARGET_REF_MAX: 120,
  LANGUAGE_MAX: 16,
  EVIDENCE_URL_MAX_ITEMS: 10,
  EVIDENCE_URL_MAX_LENGTH: 500,
  RATE_WINDOW_MS: 10 * 60 * 1000,
  RATE_MAX_REQUESTS: 8,
});

module.exports = {
  SUGGESTION_STATUS,
  SUGGESTION_TYPES,
  ALLOWED_TRANSITIONS,
  PUBLIC_LIMITS,
};
